version: '3.5'
services:
  db:
    container_name: db_instance
    image: postgres:14.3-alpine

    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      
    command: ["postgres", "-carchive_mode=on", "-cwal_level=replica", "-carchive_command=test ! -f /db_archive/%f && cp %p /db_archive/%f", "-crestore_command=cp /db_archive/%f %p" ]
    
    volumes:
      - ${PWD}/db_data:/var/lib/postgresql/data
      - ${PWD}/db_archive:/db_archive
      - ${PWD}/db_backup:/db_backup

    stdin_open: true
    tty: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db

    ports:
      - "5050:80"

    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

#    volumes:
#      - ${PGADMIN_DATA_PATH}:/var/lib/pgadmin
