version: '3.5'
services:
  db:
    container_name: db_instance
    image: postgres:14.3-alpine

    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

    stdin_open: true
    tty: true

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db

    ports:
      - "5050:80"

    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

    volumes:
      - ${PGADMIN_DATA_PATH}:/var/lib/pgadmin
